backend/controllers/AuthController.php
<?php

namespace backend\controllers;

use common\auth\Identity;
use core\services\auth\AuthService;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use core\forms\auth\LoginForm;
use yii\filters\AccessControl;
use DomainException;
use yii\web\Response;

class AuthController extends Controller
{
    private AuthService $auth_service;

    public function __construct($id, $module, AuthService $service, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->auth_service = $service;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['login'],
                        'allow'   => true,
                        'roles'   => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                    [    // all the action are accessible to admin
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string|Response
     */
    public function actionLogin(): string|Response
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'main-login';

        $form = new LoginForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $user = $this->auth_service->auth($form);
                Yii::$app->user->login(new Identity($user), $form->rememberMe ? 3600 * 24 * 30 : 0);

                return $this->goBack();
            } catch (DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('login', [
            'model' => $form,
        ]);
    }

    /**
     * @return Response
     */
    public function actionLogout(): Response
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use core\entities\Search;
use core\forms\SearchForm;
use core\services\user\UserManageService;
use DomainException;
use RuntimeException;
use Yii;
use yii\base\Action;
use yii\data\ActiveDataProvider;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use core\helpers\UserHelper;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    private UserManageService $service;

    public function __construct(string $id, $module, UserManageService $service, array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['error'],
                        'allow'   => true,
                    ],
                    [
                        'allow'   => true,
                        'roles'   => ['Dashboard'],
                    ],
                    [    // all the action are accessible to admin
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'logout'   => ['post'],
                    'language' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex(): string
    {
        return $this->render('index');
    }

    public function actionSearch(): string
    {
        $form = new SearchForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $query = Search::find()
                               ->andWhere(['LIKE', 'title', $form->query])
                               ->orWhere(['LIKE', 'content', $form->query]);

                $provider = new ActiveDataProvider([
                    'query'      => $query,
                    'pagination' => [
                        'pageSize' => 10,
                    ],
                    'sort'       => [],
                ]);

                return $this->render('search', [
                    'provider' => $provider,
                    'form'     => $form
                ]);
            } catch (DomainException) {
            }
        }

        return '';
    }

    public function actionLanguage($language): Response
    {
        if ($language && in_array($language, array_keys(Yii::$app->params['backendTranslatedLanguages']))) {
            $this->service->setBackendLanguage($language);
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @param Action $action
     * @return bool
     * @throws BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        if ($action->id === 'error') {
            $this->layout = 'error';
        }

        return parent::beforeAction($action);
    }

    public function actionGetWidgetsList(): string
    {
        return $this->renderAjax('widgets-list');
    }

    public function actionAddWidget($itemIdx, $color = ''): string
    {
        if (!Yii::$app->request->isAjax) {
            throw new RuntimeException(Yii::t('main', 'The requested page does not exist.'));
        }

        $widgets = UserHelper::getSetting('widgetsLayout', []);
        $item = Yii::$app->params['dashboard_widgets'][$itemIdx];  //require($itemFile);
        $resizable = $item['resizable'] ?? 0;
        $newWidget = [
            'w' => $item['size']['width'] ?: 0,
            'h' => $item['size']['height'] ?: 0,
            'x' => 0,
            'y' => 0,
            'c' => $color,
            'resize' => $resizable,
            'auto' => 1,
            'method' => $item['method'],
            'title' => $item['title'],
            'name' => $item['name'],
            'icon' => $item['icon'],
            'widget' => $item['widget'],
        ];
        array_push($widgets, $newWidget);
        UserHelper::setSetting('widgetsLayout', $widgets);
        return 'ok';
    }

    public function actionRemoveWidget($idx)
    {
        if (!Yii::$app->request->isAjax) {
            throw new RuntimeException(Yii::t('main', 'The requested page does not exist.'));
        }
        $widgets = UserHelper::getSetting('widgetsLayout', []);
        array_splice($widgets, $idx, 1);
        UserHelper::setSetting('widgetsLayout', $widgets);
    }

    public function actionSaveWidgets()
    {
        $widgetsJson = Yii::$app->request->post('widgets');
        $widgets = json_decode($widgetsJson, true);
        if ($widgets) {
            UserHelper::setSetting('widgetsLayout', $widgets);
        }
    }

    public function actionGetSelectedWidgetsList(): string
    {
        return $this->renderAjax( 'widgets-selected-list');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use core\forms\SubscribeForm;
use core\services\newsletter\Newsletter;
use frontend\components\FrontendController;
use RuntimeException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\components\SiteAccess;
use Yii;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends FrontendController
{
    public Newsletter $newletter;

    public function __construct(string $id, $module, Newsletter $newsletter, array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->newletter = $newsletter;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['subscribe'],
                'rules' => [
                    [
                        'actions' => ['subscribe'],
                        'allow'   => true,
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            SiteAccess::class,
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'transparent'     => true,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex(): string
    {
        $this->layout = 'home';

        return $this->render('index');
    }

    public function actionSubscribe(): array
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $form                       = new SubscribeForm();
        if (Yii::$app->request->isAjax && $form->load(Yii::$app->request->post())) {
            try {
                $this->newletter->subscribe($form->email);

                return ['result' => 'success'];
            } catch (RuntimeException $e) {
                return ['result' => 'error', 'message' => $e->getMessage()];
            }
        }

        return ['result' => 'error', 'message' => 'Request error'];
    }
}

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                <?= Yii::t('main', 'Return to back or login page please.') ?>
            </p>
	        <p>
		        <?= Html::a(Yii::t('main', 'Sign out'), ['/auth/logout'], ['data-method' => 'POST']) ?>
	        </p>

        </div>
    </div>

</section>

backend/views/site/index.php
<?php

use core\helpers\UserHelper;
use zertex\gridstack\Gridstack;
use kartik\dialog\Dialog;
use yii\web\JsExpression;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = Yii::t('dashboard', 'Dashboard');

$css = '
        .grid-stack {
            margin: 0 !important;
            padding: 0 !important;
            /*border: solid 1px red;*/
        }
        .grid-stack-item {
            margin: 0 !important;
            padding: 0 !important;
            /*border: solid 1px green;*/
            overflow: hidden;
        }
        .grid-stack-item-content {
            margin: 0 !important;
            padding: 0 !important;
            overflow: hidden !important;
            left: 0 !important;
            right: 15px !important;
            /*bottom: 40px !important;*/
            /*bottom: auto !important;*/
        }
        
        .moveButton {
            font-size:12px;
            color:#999;
            cursor: pointer;
            margin-right:5px;
            display: inline-block;
        }
        .moveButton:hover {
            color:#333;
        }

        .user128 {
            width: 128px;
            height: 128px;
        }
        
        .big_drop .select2-results ul {
            max-height: 500px !important;
            min-height: 500px !important;
            height: 500px !important;
        }  
';
$this->registerCss($css);

$addWidgetUrl = Url::toRoute('/site/add-widget');
$removeWidgetUrl = Url::toRoute('/site/remove-widget');
$js = <<<JS
    var AddWidgetDialog;
    var RemoveWidgetDialog;

    function addWidget(itemIdx, colorId)
    {
        var color = $("#"+colorId).val();
        $.ajax({
            method: "GET",
            data: {itemIdx: itemIdx, color: color},
            url: "{$addWidgetUrl}"
        })
        .done(function(data){
            AddWidgetDialog.close();
            document.location.reload();
        });
        return false;
    }

    function removeWidget(idx)
    {
        $.ajax({
            method: "GET",
            data: {idx: idx},
            url: "{$removeWidgetUrl}"
        })
        .done(function(data){
            RemoveWidgetDialog.close();
            document.location.reload();
        });
        return false;
    }
JS;

$this->registerJs($js, $this::POS_HEAD);

$saveWidgetsUrl = Url::toRoute('/site/save-widgets');
$js2 = '
    $("#addWidgetButton").on("click", function() {
        krajeeDialog.dialog(
            "",
            function (result) {alert(result);}
        );
    });
    
    $("#removeWidgetButton").on("click", function() {
        krajeeDialogRemove.dialog(
            "",
            function (result) {alert(result);}
        );
    });

    $(".grid-stack").on("change", function(event, items) {
        var widgets = [];

        $(".grid-stack-item.ui-draggable").each(function () {
            var $this = $(this);
            widgets.push({
                x: $this.attr("data-gs-x"),
                y: $this.attr("data-gs-y"),
                w: $this.attr("data-gs-width"),
                h: $this.attr("data-gs-height"),
                c: $this.attr("data-color"),
                title: $this.attr("data-title"),
                name: $this.attr("data-name"),
                method: $this.attr("data-method"),
                resize: $this.attr("data-resize"),
                widget: $this.attr("data-widget"),
                icon: $this.attr("data-icon"),
            });
        });
        var widgetsJson = JSON.stringify(widgets);
        $.ajax({
            method: "POST",
            data: {widgets: widgetsJson},
            url: "' . $saveWidgetsUrl . '",
        })
        .done(function(data){
        });
    });
';

$this->registerJs($js2, $this::POS_READY);

$formatJs = <<<JS
var formatRepo = function (repo) {
    if (repo.loading) {
        return repo.text;
    }
    var markup =
'<div class="row">' + 
    '<div class="col-sm-12">' +
        '<b style="margin-left:5px">' + repo.text + '</b>' + 
    '</div>' +
'</div>';
    if (repo.description) {
      markup += '<h5>' + repo.description + '</h5>';
    }
    return '<div style="overflow:hidden;">' + markup + '</div>';
};
var formatRepoSelection = function (repo) {
    return repo.full_name || repo.text;
}
JS;
$this->registerJs($formatJs, $this::POS_HEAD);
?>

<div class="site-index">

    <?= Dialog::widget([
        'options' => [
            'title' => Yii::t('main', 'Add widget'),
            'buttons' => [
                [
                    'id' => 'cancel-1',
                    'label' => Yii::t('main', 'Cancel'),
                    'action' => new JsExpression('function(dialog) {
                        dialog.close();
                    }')
                ],
            ],
            'onshown' => new JsExpression("function(dialog){
                var url = '" . Url::toRoute('/site/get-widgets-list') . "';
                $.ajax({
                    method: 'POST',
                    url: url,
                })
                .done(function(data){
                    dialog.getModalBody().html(data);
                    AddWidgetDialog = dialog;
                });
            }"),
        ],
    ]); ?>

    <?= Dialog::widget([
        'libName' => 'krajeeDialogRemove',
        'options' => [
            'title' => Yii::t('main', 'Remove widget'),
            'type' => Dialog::TYPE_DANGER,
            'buttons' => [
                [
                    'id' => 'cancel-1',
                    'label' => Yii::t('main', 'Cancel'),
                    'action' => new JsExpression('function(dialog) {
                        dialog.close();
                    }')
                ],
            ],
            'onshown' => new JsExpression("function(dialog){
                var url = '" . Url::toRoute('/site/get-selected-widgets-list') . "';
                $.ajax({
                    method: 'POST',
                    url: url,
                })
                .done(function(data){
                    dialog.getModalBody().html(data);
                    RemoveWidgetDialog = dialog;
                });
            }"),
        ],
    ]); ?>

    <?php
    $gridStack = Gridstack::begin([
        'options'       => ['class' => 'grid-stack'],
        'clientOptions' => [
            'cellHeight'     => 22,
            'verticalMargin' => 15,
            'handle'         => '.moveHandle',
        ],
    ]);
    $widgets = UserHelper::getSetting('widgetsLayout', []);
    foreach ($widgets as $widget) {
        $widgetData = [
            'class'=>'grid-stack-item',
            'data-gs-width'=>$widget['w'],
            'data-gs-height'=>$widget['h'],
            'data-gs-x'=>$widget['x'],
            'data-gs-y'=>$widget['y'],
            'data-method' => $widget['method'],
            'data-title' => $widget['title'],
            'data-color' => $widget['c'],
            'data-resize' => $widget['resize'],
            'data-widget' => $widget['widget'],
            'data-icon' => $widget['icon'],
            'data-name' => $widget['name'],
        ];
        // Disable resize if need
        if ($widget['resize'] == 0) {
            $widgetData['data-gs-no-resize'] = 'y';
        }

        if (isset($widget['auto']) && $widget['auto'] == 1) {
            $widgetData['data-gs-auto-position'] = 'y';
        }

        // Remove (), if exists
        $widget['method'] = str_replace('()', '', $widget['method']);
        // Echo widget data
        echo $gridStack->beginWidget($widgetData);
        echo call_user_func($widget['widget'] . '::' . $widget['method'], $widget['c']);
        echo $gridStack->endWidget();
    }
    ?>

    <?php Gridstack::end(); ?>

    <div class="clearfix"></div>
    <hr>

    <div class="row" style="text-align: right; padding-right:15px;">
        <button class="btn btn-default" id="addWidgetButton"><i class="fa fa-plus"></i></button>
        <button class="btn btn-default" id="removeWidgetButton"><i class="fa fa-minus"></i></button>
    </div>

</div>

backend/views/site/login.php
<?php

use common\models\LoginForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Sign in', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>

        <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                in using Google+</a>
        </div>
        <!-- /.social-auth-links -->

        <a href="#">I forgot my password</a><br>
        <a href="register.html" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

backend/views/site/search.php
<?php

use core\entities\Search;
use core\forms\SearchForm;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\StringHelper;

/* @var $this yii\web\View */
/* @var $provider yii\data\ActiveDataProvider */
/* @var $form SearchForm */

$title = Yii::t('main', 'Search results');
$this->title = $title . ' > ' . Html::encode($form->query);
$this->params['breadcrumbs'][] = $title;
?>
<div class="blog-post-index">

    <div class="box">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $provider,
                'showHeader' => false,
                'options' => [
                	'style' => 'word-wrap:break-word;',
                ],
                'tableOptions' => [
					'class' => 'table',
				],
                'columns' => [
                    [
                        'attribute' => 'title',
                        'value' => function (Search $model) {
                            return Html::a(Html::tag('h3', $model->title), [$model->url]) . StringHelper::truncateWords(strip_tags($model->content), 60, '...');
                        },
                        'format' => 'raw',
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>

backend/views/site/widgets-list.php
<?php

use yii\helpers\Html;
use backend\helpers\DashboardHelper;
use yii\web\View;

/**
 * @var $this View
 * @var $wl array
 */

list($widgetsCounter, $widgetsInfo) = DashboardHelper::getAllWidgets();
?>

<div class="row">
    <div class="col-md-6">
        <h4><?= Yii::t('main', 'Counters widgets') ?></h4>

        <div style="margin-bottom:15px;">
            <?= Html::dropDownList('colorCounter', 'blue', DashboardHelper::getExtColors(), [
                'id' => 'colorCounter',
                'class' => 'form-control',
            ]) ?>
        </div>
        <?= $widgetsCounter ?>
    </div>
    <div class="col-md-6">
        <h4><?= Yii::t('main', 'Info widgets') ?></h4>
        <div style="margin-bottom:15px;">
            <?= Html::dropDownList('colorInfo', 'primary', DashboardHelper::getColors(), [
                'id' => 'colorInfo',
                'class' => 'form-control',
            ]) ?>
        </div>
        <?= $widgetsInfo ?>
    </div>
</div>

backend/views/site/widgets-selected-list.php
<?php

/**
 * @var $this \yii\web\View
 */

use core\helpers\UserHelper;

$widgets = UserHelper::getSetting('widgetsLayout', []);
$i       = 0;
?>

<?php foreach ($widgets as $widget) : ?>

    <a href="#" onClick="removeWidget(<?= $i ?>)"><?= $widget['name'] ?></a><br>

    <?php
    $i++;
endforeach;
?>