backend/controllers/ModuleController.php
<?php
/**
 * Created by Error202
 * Date: 17.08.2018
 */

namespace backend\controllers;

use core\entities\ModuleRecord;
use core\services\ModuleService;
use Yii;
use yii\base\ErrorException;
use yii\db\Exception;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Modules Management
 * Class ModuleController
 * @package backend\controllers
 */
class ModuleController extends Controller
{
    /**
     * @var ModuleService Modules management service
     */
    private $service;

    public function __construct(string $id, $module, ModuleService $service, array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['list', 'disable', 'enable', 'delete', 'search'],
                        'allow'   => true,
                        'roles'   => ['ModuleManagement'],
                    ],
                    [    // all the action are accessible to admin
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete'  => ['POST'],
                    'disable' => ['POST'],
                    'enable'  => ['POST'],
                    'install' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * List of modules
     * @return string
     */
    public function actionList(): string
    {
        $modules = Yii::$app->moduleManager->getModules();

        return $this->render('list', [
            'modules' => $modules,
        ]);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws ErrorException
     * @throws Exception
     */
    public function actionDelete($id): Response
    {
        $module = $this->findModel($id);
        $this->service->delete($module);

        return $this->redirect(['module/list']);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionDisable($id): Response
    {
        $module = $this->findModel($id);
        $this->service->disable($module);

        return $this->redirect(['module/list']);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionEnable($id): Response
    {
        $module = $this->findModel($id);
        $this->service->enable($module);

        return $this->redirect(['module/list']);
    }

    public function actionSearch(): string
    {
        $message = null;
        try {
            $list    = file_get_contents('http://zertex.ru/zxcms/modules.txt');
            $links   = array_filter(explode('|', $list));
            $modules = [];
            foreach ($links as $link) {
                $manifest = file_get_contents($link);
                $manifest = eval(str_replace('<?php', '', $manifest));

                if (isset($manifest['enabled']) && $manifest['enabled'] == false) {
                    continue;
                }

                $languageFile = str_replace('manifest.php', 'messages/' . Yii::$app->language . '/' . $manifest['name'] . '.php', $link);
                try {
                    $language = file_get_contents($languageFile);
                    $language = eval(str_replace('<?php', '', $language));
                    $manifest['locale_name'] = $language[$manifest['name']] ?? $manifest['name'];
                    $manifest['locale_description'] = $language[$manifest['description']] ?? $manifest['description'];
                } catch (\Exception) {
                    $manifest['locale_name'] = $manifest['name'];
                    $manifest['locale_description'] = $manifest['description'];
                }

                $modules[] = $manifest;
            }
        } catch (\Exception) {
            $modules = [];
            $message = Yii::t('main', 'Available modules not found');
        }

        return $this->render('remote-list', [
            'modules' => $modules,
            'message' => $message,
        ]);
    }

    /**
     * @param $id
     * @return ModuleRecord
     * @throws NotFoundHttpException
     */
    protected function findModel($id): ModuleRecord
    {
        if (($model = ModuleRecord::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested module does not exist.');
    }
}

backend/views/module/list.php
<?php
/**
 * Created by Error202
 * Date: 17.08.2018
 */

use core\entities\ModuleRecord;
use yii\helpers\Html;
use core\helpers\ModuleHelper;
use kartik\dialog\Dialog;
use yii\web\View;

/**
 * @var $this View
 * @var $modules ModuleRecord[]
 */

$this->title                   = Yii::t('main', 'Modules');
$this->params['breadcrumbs'][] = $this->title;

$message = Yii::t('main', 'To remove the module, use the following command in the SSH console:');
$js = <<<JS
    $(".delete-button").on('click', function () {
        var name = $(this).data('name');
        krajeeDialog.alert('{$message}' + "\\n" + '<pre><code>php yii module/remove ' + name + '</code></pre>'); 
    });
JS;
$this->registerJs($js, $this::POS_READY);
?>

<?=  Dialog::widget([
    'options' => [],
]);
?>

<div class="row">

    <?php foreach ($modules as $module) : ?>

        <?php
        $color = $module->isEnabled() ? '#00aced' : '#cccccc';
        if ($module->isDisabled()) {
            ModuleHelper::addModuleAdminTranslation($module->name);
        }

        $module_name        = in_array($module->name, array_keys(Yii::$app->getI18n()->translations)) ? Yii::t($module->name, $module->name) : $module->name;
        $module_description = in_array($module->name, array_keys(Yii::$app->getI18n()->translations)) ? Yii::t($module->name, $module->description) : $module->description;
        ?>

        <div class="col-md-4">

            <div class="card">
                <div class="card-header">
                    <h3 class="box-title"><i class="fa fa-power-off" aria-hidden="true"
                                             style="color: <?= $color ?>"></i> <?= $module_name ?></h3>
                </div>
                <div class="card-body">
                    <?= $module_description ?>
                </div>
                <div class="card-footer" style="text-align: right">
                    <?php if (!$module->isSystem()) : ?>
                        <?php if ($module->isEnabled()) : ?>
                            <?= Html::a(Yii::t('main', 'Disable'), ['module/disable', 'id' => $module->id], [
                                'class' => 'btn btn-default btn-sm',
                                'data'  => [
                                    'method' => 'post',
                                ],
                            ]) ?>
                        <?php else : ?>
                            <?= Html::a(Yii::t('main', 'Enable'), ['module/enable', 'id' => $module->id], [
                                'class' => 'btn btn-default btn-sm',
                                'data'  => [
                                    'method' => 'post',
                                ],
                            ]) ?>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if (!$module->isSystem()) : ?>
                        <?= Html::button(Yii::t('buttons', 'Delete'), [
                            'class' => 'btn btn-danger btn-sm delete-button',
                            'data-name' => $module->name,
                        ]) ?>
                    <?php else : ?>
                        <?= Html::button(Yii::t('buttons', 'Delete'), [
                            'class' => 'btn btn-danger btn-sm disabled',
                            'data-name' => $module->name,
                        ]) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

backend/views/module/remote-list.php
<?php
/**
 * Created by Error202
 * Date: 17.08.2018
 */

use yii\helpers\Html;
use kartik\dialog\Dialog;
use yii\web\View;

/**
 * @var $this View
 * @var $modules array
 * @var $message string
 */

$this->title                   = Yii::t('main', 'Available Modules');
$this->params['breadcrumbs'][] = $this->title;

$messageInstall = Yii::t('main', 'To install the module, use the following command in the SSH console:');
$js = <<<JS
    $(".install-button").on('click', function () {
        var name = $(this).data('name');
        krajeeDialog.alert('{$messageInstall}' + "\\n" + '<pre><code>php yii module/install ' + name + '</code></pre>'); 
    });
JS;
$this->registerJs($js, $this::POS_READY);
?>

<?php if ($message) : ?>
    <div><?= $message ?></div>
<?php endif; ?>

<?=  Dialog::widget([
        'options' => [],
    ]);
?>

<div class="row">

    <?php foreach ($modules as $module) : ?>

        <?php
        $color = '#00aced';

        $module_name        = $module['locale_name'];
        $module_description = $module['locale_description'];
        ?>

        <div class="col-md-4">

            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><?= $module_name ?></h3>
                </div>
                <div class="box-body">
                    <?= $module_description ?>
                </div>
                <div class="box-footer" style="text-align: right">
                    <?php if (Yii::$app->moduleManager->isExists($module['name'])) : ?>
                        <?= Html::button(Yii::t('main', 'Installed'), [
                            'class' => 'btn btn-default btn-sm disabled',
                        ]) ?>
                    <?php else : ?>
                        <?= Html::button(Yii::t('main', 'Install'), [
                            'class' => 'btn btn-success btn-sm install-button',
                            'data-name' => $module['name'],
                        ]) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>